### PR TITLE
merge master into lily

### PR DESCRIPTION
**Pull request by frrist**

### CODE REVIEW

**Comment by iand** [comment]
Didn't we just do this? Why do I see the same commits like "vector benchmarking" that I thought we merged before?

**Comment by frrist** [comment]
The changes look right, but the commits do seem a bit odd..

**Comment by iand** [comment]
LGTM but perhaps wait for your recent fixes to be merged and include those too?

**Review by iand — APPROVED** [review]

**Comment by frrist** [comment]
Yup, will be sure to include them here before merging into lily.

**Pull request merged**
