### PR TITLE
feat: Add flag to remove lock on startup

### PR DESCRIPTION
**Pull request by placer14**
Something temporary to fix `2020-10-05T18:18:04.584Z        INFO    schedule        schedule/scheduler.go:79        task not started: lock not acquired     {"task": "ChainHeadIndexer"}`

### CODE REVIEW

**Comment by iand** [comment]
This is the message I would expect if another indexer is running.

**Comment by placer14** [comment]
There's definitely not another indexer. This also doesn't appear to be working as I expected... :/

**Comment by iand** [comment]
Can you rebase to make it easier to see the change?

**Comment by placer14** [comment]
Alright, closing this and will revisit if this becomes a bigger problem later.

**Pull request closed without merging**
