### PR TITLE
build(devnet): support building visor for devnets

### LINKED ISSUE #418: Support non-mainnet networks
### Description

Visor statically imports Lotus packages to call some functions directly (such as `vm.ComputeGasOutputs`). These will use the network parameters defined at build time, controlled using build tags in the Lotus source. The default build will result in mainnet parameters being used for these calls. We should allow other networks to be specified when building.

### Where to begin

Look at Lotus makefile to see which build tags need to be set

### PR DESCRIPTION
**Pull request by frrist**
closes #418 
Verified this runs as expected locally against the calibration network.

### CODE REVIEW

**Comment by iand** [comment]
Have you verified that we are not making assumptions about mainnet. I am thinking particularly of areas where we create a fake VM to calculate gas costs using the network's pricing scheme, such as https://github.com/filecoin-project/sentinel-visor/blob/master/lens/util/repo.go#L381 or https://github.com/filecoin-project/sentinel-visor/blob/master/lens/lotus/api.go#L289 . 

I assume correct genesis loading (such as https://github.com/filecoin-project/sentinel-visor/blob/master/lens/util/repo.go#L96) is handled automatically by the build tags?

**Comment by frrist** [comment]
I have modified the `Version` field of Visor to print more helpful information about the version of lotus it was built for. These values are pulled directly from lotus.
**Mainnet**
```
NAME:
   visor - Filecoin Chain Monitoring Utility

USAGE:
   visor [global options] command [command options] [arguments...]

VERSION:
   VisorVersion:           v0.6.7+4-g99d8e9a
   NewestNetworkVersion:   13
   GenesisFile:            mainnet.car
   DevNet:                 false
   UserVersion:            1.11.0-dev+mainnet
   UpgradeSchedule: 
    Height: 41280, Network: 1, Expensive: false
    Height: 51000, Network: 2, Expensive: false
    Height: 94000, Network: 3, Expensive: false
    Height: 130800, Network: 3, Expensive: false
    Height: 138720, Network: 4, Expensive: false
    Height: 140760, Network: 5, Expensive: false
    Height: 148888, Network: 5, Expensive: false
    Height: 170000, Network: 6, Expensive: false
    Height: 265200, Network: 7, Expensive: false
    Height: 272400, Network: 8, Expensive: false
    Height: 336458, Network: 9, Expensive: false
    Height: 550321, Network: 10, Expensive: false
    Height: 665280, Network: 11, Expensive: false
    Height: 712320, Network: 12, Expensive: false
    Height: 9999999, Network: 13, Expensive: false
```
**Calibrationnet**
```
NAME:
   visor - Filecoin Chain Monitoring Utility

USAGE:
   visor [global options] command [command options] [arguments...]

VERSION:
   VisorVersion:           v0.6.7+4-g99d8e9a
   NewestNetworkVersion:   13
   GenesisFile:            calibnet.car
   DevNet:                 true
   UserVersion:            1.11.0-dev+calibnet
   UpgradeSchedule: 
    Height: 30, Network: 4, Expensive: false
    Height: 60, Network: 5, Expensive: false
    Height: 90, Network: 6, Expensive: false
    Height: 100, Network: 7, Expensive: false
    Height: 220, Network: 8, Expensive: false
    Height: 300, Network: 9, Expensive: false
    Height: 600, Network: 10, Expensive: false
    Height: 114000, Network: 11, Expensive: false
    Height: 193789, Network: 12, Expensive: false
    Height: 9999999, Network: 13, Expensive: false

```
This confirms we are using the correct genesis block.

As for the Network version we get from here: https://github.com/filecoin-project/sentinel-visor/blob/master/lens/util/network.go#L13. The values returned by `DefaultUpgradeSchedule` are specified by the build flags, from the above they also appear to be valid.

**Comment by iand** [comment]
Cool

**Review by iand — APPROVED** [review]

**Comment by iand** [comment]
Surprised that the upgrade epoch for network 13 is not set in calibnet

**Comment by iand** [comment]
> Surprised that the upgrade epoch for network 13 is not set in calibnet

Maybe it's because we are using lotus master?

**Comment by iand** [comment]
Make sure we have upgraded lotus dependency before using this. https://github.com/filecoin-project/lotus/blob/master/build/params_calibnet.go#L49 shows that the calibnet upgrade epoch should be 321519

**Pull request merged**
