### PR TITLE
update sql lens to archival interface

### PR DESCRIPTION
**Pull request by willscott**
This change updates the SqlRepo Lens to provide a datastore backing using the
same code as in
https://github.com/filecoin-project/statediff/pull/119
and
https://github.com/ribasushi/ltsh/tree/psql_fullcapture

ref
https://github.com/ribasushi/ltsh/commit/4654e05d922

The changed interface uses a separate table for tracking 'current', and headers.

Possible remaining TODO is to improve the query used for getting the
current tipset to respect the lookback parameter and instead find the
tipset at height `n` before the most recently known tipset.

### CODE REVIEW

**Comment by iand** [comment]
@willscott does this need updating for more recent versions of the postgresql block store?

**Comment by willscott** [comment]
yes probably. waiting for @ribasushi to indicate the interface has stabilized.

**Comment by ribasushi** [comment]
Yeah keep open please, entirely different layout coming "any moment now"

**Comment by frrist** [comment]
Going to close this to keep the PR backlog tidy, can reopen when we are ready to complete this work.

**Comment by ribasushi** [comment]
@frrist this was done in https://github.com/filecoin-project/sentinel-visor/pull/409, we just forgot to close this one

**Pull request closed without merging**
