### PR TITLE
chore: Avoid ingesting binary and unused data

### LINKED ISSUE #204: Avoid ingesting binary, unused data
We should be dropping as much information as we can when ingesting chain data.

The first example I have is the Proof fields in jsonb in the parsed_messages table, which for a full chain seems to amount to a lot of data. The messages table also stores the binary parameters (which is redundant if it is also stored as parsed data?).

There are binary columns like `ticket` and `election_proof` in the block_headers table. We are also storing the drand binary randomness value.

### Acceptance Criteria
- Remove `ticket` and `election_proof` from block_headers
- Remove `params` from messages
- Remove `drand_entries` entire
- Remove `return` in receipts

### PR DESCRIPTION
**Pull request by frrist**
close #204

### CODE REVIEW

**Review by willscott — APPROVED** [review]

**Review by iand — COMMENTED** [review]
Why do we want to drop `drand_block_entries`? I thought that mapped blocks to the drand round number, which seems useful to keep. #204 doesn't mention deleting it.

**Comment by frrist** [comment]
Thanks @iand I missed that in my read of the issue. I have reverted the removal of the `drand_block_entries`.

**Review by iand — APPROVED** [review]

**Comment by placer14** [comment]
Does https://github.com/filecoin-project/sentinel-visor/pull/241/commits/0cf9ff32abdab195fdfdb5fc4f33d5666109769e look okay to you, @frrist ?

**Comment by frrist** [comment]
Yup looks fine assuming it works when ran.

**Comment by placer14** [comment]
It does! CI proves the migrations now: https://app.circleci.com/pipelines/github/filecoin-project/sentinel-visor/834/workflows/2326c51e-554c-4ea8-97b2-317c25811bd9/jobs/1816/parallel-runs/0/steps/0-109

**Review by placer14 — APPROVED** [review]

**Pull request merged**
