### PR TITLE
Update Lotus v1.4.2

### LINKED ISSUE #384: carrepo not working for the chaineconomics task
### Describe the bug:

I'm trying the carrepo lens on the repo at `https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car`
and I think something is trying to write but failing.

### Steps to Reproduce:

```
$ ./visor --db "" --repo-read-only --lens carrepo --repo /lotus/minimal_finality_stateroots_latest.car walk --tasks chaineconomics
2021-02-15T21:40:37.751Z        WARN    chainstore      store/store.go:578      no heaviest tipset found, using [bafy2bzacedkjqhl46othdltxxhhqarczkkmkhfiezilw2erqyvwj5fknitlse]
2021-02-15T21:40:37.751Z        INFO    chainstore      store/store.go:583      New heaviest tipset! [bafy2bzacedkjqhl46othdltxxhhqarczkkmkhfiezilw2erqyvwj5fknitlse] (height=503621)
2021-02-15T21:40:37.751Z        WARN    visor   commands/walk.go:94     database not specified, data will not be persisted
2021-02-15T21:40:37.751Z        INFO    schedule        schedule/scheduler.go:124       running task    {"task": "Walker"}
2021-02-15T21:40:37.751Z        DEBUG   chain   chain/walker.go:71      found tipset    {"height": "503621"}
2021-02-15T21:40:37.754Z        WARN    bufbs   bufbstore/buf_bstore.go:44      one of the stores is not viewable; running less efficiently
2021-02-15T21:40:37.757Z        WARN    vm      vm/runtime.go:145       VM.Call failure: failed to put cbor object: failed to write data to disk (FATAL): invalid cid version number: 12962 (FATAL):
    github.com/filecoin-project/lotus/chain/vm.(*Runtime).StorePut
        /home/pl/.asdf/installs/golang/1.15.7/packages/pkg/mod/github.com/filecoin-project/lotus@v1.5.0-pre1/chain/vm/runtime.go:133
2021-02-15T21:40:37.757Z        ERROR   chain   chain/economics.go:45   error received while extracting chain economics, closing lens   {"error": "get circulating supply: [from=f3rfurvushzaeeuo5yxtopcsrqtobve2xgae4n7tspgmnlzwowhhwq26xinsfkc7yk27bzclxh35knrp22hyqa,to=f01800,n=459581,m=6,h=503621] fatal error: failed to put cbor object: failed to write data to disk (FATAL): invalid cid version number: 12962 (FATAL)", "errorVerbose": "get circulating supply:\n    github.com/filecoin-project/sentinel-visor/tasks/chain.ExtractChainEconomicsModel\n        /home/pl/sentinel-visor/tasks/chain/economics.go:29\n  - [from=f3rfurvushzaeeuo5yxtopcsrqtobve2xgae4n7tspgmnlzwowhhwq26xinsfkc7yk27bzclxh35knrp22hyqa,to=f01800,n=459581,m=6,h=503621] fatal error:\n    github.com/filecoin-project/lotus/chain/vm.(*VM).ApplyMessage\n        /home/pl/.asdf/installs/golang/1.15.7/packages/pkg/mod/github.com/filecoin-project/lotus@v1.5.0-pre1/chain/vm/vm.go:530\n  - failed to put cbor object: failed to write data to disk (FATAL): invalid cid version number: 12962 (FATAL):\n    github.com/filecoin-project/lotus/chain/vm.(*Runtime).StorePut\n        /home/pl/.asdf/installs/golang/1.15.7/packages/pkg/mod/github.com/filecoin-project/lotus@v1.5.0-pre1/chain/vm/runtime.go:133"}
2021-02-15T21:40:37.757Z        ERROR   chain   chain/indexer.go:223    task returned with error        {"height": 503621, "task": "chaineconomics", "error": "get circulating supply: [from=f3rfurvushzaeeuo5yxtopcsrqtobve2xgae4n7tspgmnlzwowhhwq26xinsfkc7yk27bzclxh35knrp22hyqa,to=f01800,n=459581,m=6,h=503621] fatal error: failed to put cbor object: failed to write data to disk (FATAL): invalid cid version number: 12962 (FATAL)"}
2021-02-15T21:40:37.757Z        ERROR   schedule        schedule/scheduler.go:133       task exited with failure        {"task": "Walker", "error": "walk chain: notify tipset: get circulating supply: [from=f3rfurvushzaeeuo5yxtopcsrqtobve2xgae4n7tspgmnlzwowhhwq26xinsfkc7yk27bzclxh35knrp22hyqa,to=f01800,n=459581,m=6,h=503621] fatal error: failed to put cbor object: failed to write data to disk (FATAL): invalid cid version number: 12962 (FATAL)"}
```

### PR DESCRIPTION
**Pull request by frrist**
### What
- Update to lotus v1.4.2 03a5813224f0b48b07e3898abdb89d2b2583a1bc
  - Ensure the genesis block is set on the chain store [`03a5813` (#385)](https://github.com/filecoin-project/sentinel-visor/pull/385/commits/03a5813224f0b48b07e3898abdb89d2b2583a1bc#diff-bc703188359ac3cd735e35dfd43c3a10733026e14808a032a239837b37b83d2aR96-R103) fixes #384 
  - Put the context where lotus wants it [`03a5813` (#385)](https://github.com/filecoin-project/sentinel-visor/pull/385/commits/03a5813224f0b48b07e3898abdb89d2b2583a1bc#diff-a6fe45980f5156c43c13fa02762c2d9a4106f6a11376d239cfe47f825260eb17R79) 
- Generate Test Vectors to exercise `chaineconomics` and `rewardactor` tasks (which work now after upgrading lotus!!) f4f182fa2653da89f01fb08f6f00cc4ee7a01b35

### CODE REVIEW

**Comment by thattommyhall** [comment]
I think this again gets us closer, I now see this error 

```
2021-02-16T14:26:49.191Z        WARN    chainstore      store/store.go:578      no heaviest tipset found, using [bafy2bzacedkjqhl46othdltxxhhqarczkkmkhfiezilw2erqyvwj5fknitlse]
2021-02-16T14:26:49.191Z        INFO    chainstore      store/store.go:583      New heaviest tipset! [bafy2bzacedkjqhl46othdltxxhhqarczkkmkhfiezilw2erqyvwj5fknitlse] (height=503621)
2021-02-16T14:26:49.191Z        WARN    visor   commands/walk.go:94     database not specified, data will not be persisted
2021-02-16T14:26:49.191Z        INFO    schedule        schedule/scheduler.go:124       running task    {"task": "Walker"}
2021-02-16T14:26:49.191Z        DEBUG   chain   chain/walker.go:71      found tipset    {"height": "503621"}
2021-02-16T14:26:49.192Z        ERROR   chain   chain/economics.go:45   error received while extracting chain economics, closing lens   {"error": "get circulating supply: failed to setup pre-ignition vesting schedule: getting genesis block: datastore: key not found", "errorVerbose": "get circulating supply:\n    github.com/filecoin-project/sentinel-visor/tasks/chain.ExtractChainEconomicsModel\n        /home/pl/sentinel-visor/tasks/chain/economics.go:29\n  - failed to setup pre-ignition vesting schedule:\n    github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).GetVMCirculatingSupplyDetailed\n        /home/pl/.asdf/installs/golang/1.15.7/packages/pkg/mod/github.com/filecoin-project/lotus@v1.4.2-rc1/chain/stmgr/stmgr.go:1244\n  - getting genesis block:\n    github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).setupGenesisVestingSchedule\n        /home/pl/.asdf/installs/golang/1.15.7/packages/pkg/mod/github.com/filecoin-project/lotus@v1.4.2-rc1/chain/stmgr/stmgr.go:956\n  - datastore: key not found"}
2021-02-16T14:26:49.192Z        ERROR   chain   chain/indexer.go:223    task returned with error        {"height": 503621, "task": "chaineconomics", "error": "get circulating supply: failed to setup pre-ignition vesting schedule: getting genesis block: datastore: key not found"}
2021-02-16T14:26:49.192Z        ERROR   schedule        schedule/scheduler.go:133       task exited with failure        {"task": "Walker", "error": "walk chain: notify tipset: get circulating supply: failed to setup pre-ignition vesting schedule: getting genesis block: datastore: key not found"}
```

**Comment by frrist** [comment]
> failed to setup pre-ignition vesting schedule: getting genesis block: datastore: key not found

It looks like we need to set the genesis block on the ChainStore before constructing the StateManager with it.

**Comment by frrist** [comment]
Added some vectors to make the failures easily reproducible, need to fix the genesis block error and this should be good to go.

**Comment by frrist** [comment]
Everything should be wae now. Feel free to merge on approval.

**Review by iand — APPROVED** [review]

**Pull request merged**
